#!/bin/bash

negationlist=( none noone nothing nobody neither nowhere never don\'t doesn\'t didn\'t aren\'t isn\'t wasn\'t weren\'t haven\'t hasn\'t hadn\'t won\'t shouldn\'t wouldn\'t can\'t couldn\'t ain\'t dont doesnt didnt arent isnt wasnt werent havent hasnt hadnt wont shouldnt wouldnt cant couldnt aint not )

for m in "${negationlist[@]}"
do
	grep -w -h $m ~/Desktop/Courses/TeamLab/nohashtag/train/*.csv > ~/Desktop/Courses/TeamLab/nohashtag/train-onlyneg/$m.csv
	
	grep -w -h $m ~/Desktop/Courses/TeamLab/nohashtag/test/*.csv > ~/Desktop/Courses/TeamLab/nohashtag/test-onlyneg/$m.csv

done
